name: Sync Image to Aliyun  Example
#4
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-p4uvabvsouo615nw.cn-qingdao.personal.cr.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false
#lobehub/lobe-chat
    - name: Use Skopeo Tools Sync Image to Docker Hub 1
      run: |
         skopeo copy docker://docker.io/lobehub/lobe-chat:latest docker://crpi-p4uvabvsouo615nw.cn-qingdao.personal.cr.aliyuncs.com/sijin_docker/lobe-chat:latest
#voapi/voapi
    - name: Use Skopeo Tools Sync Image to Docker Hub 2
      run: |
         skopeo copy docker://docker.io/voapi/voapi:latest docker://crpi-p4uvabvsouo615nw.cn-qingdao.personal.cr.aliyuncs.com/sijin_docker/voapi:latest 
         
 #blinkospace/blinko
    - name: Use Skopeo Tools Sync Image to Docker Hub 3
      run: |
         skopeo copy docker://docker.io/blinkospace/blinko:latest docker://crpi-p4uvabvsouo615nw.cn-qingdao.personal.cr.aliyuncs.com/sijin_docker/blinko:latest 
                 
         
